const CODES = {};
// users
CODES._USER_NOT_FOUND_ = 100;
CODES._EMAIL_OR_PASSWORD_IS_INCORRECT_= 101;
CODES._WRONG_USER_CREDENTIALS_= 109;
CODES._CANT_REFRESH_TOKEN_ = 113;
CODES._INVALID_REFRESH_TOKEN_ = 114;
CODES._NOT_VERIFIED_TO_CHANGE_PASSWORD_ = 115;

// client
CODES._UNAUTHORIZED_ = 430;
CODES._WRONG_PARAMS_= 466;
CODES._UNEXPECTED_PARAMS_= 467;
CODES._RESOURCE_NOT_FOUND_ = 480;

// sm
CODES._CANT_AUTHENTICATE_WITH_FACEBOOK_= 801;
CODES._CANT_AUTHENTICATE_WITH_APPLE_= 802;

//db
CODES._UNKNOWN_ERROR_= 1000;
CODES._ITEMS_NOT_FOUND_= 1008;
CODES._USER_ALREADY_EXISTS_= 1009;
CODES._SETTINGS_OF_USER_ALREADY_EXISTS_ = 1010;
CODES._CANT_INSERT_NEW_VALUE_ = 1051;

// other
CODES._CANT_VERIFY_JWT_ = 2001;
CODES._CANT_CREATE_JWT_ = 2003;
CODES._CANT_HASH_PASSWORD_ = 2002;
CODES._CANT_SEND_EMAIL_ = 2003;
CODES._CANT_VERIFY_RESET_TOKEN_ = 2004;
CODES._WRONG_RESET_PASSWORD_TOKEN_ = 2005;

module.exports = CODES;
